name: OIDF Publish
on:
  push:
    branches:
      - main
    # Only deploy when sync/specs changes (set by publish-prep)
    paths:
      - 'sync/specs/**'
  workflow_dispatch:

jobs:
  deploy:
    name: OIDF-Deploy
    runs-on: ubuntu-latest
    environment: openid.net/specs/
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update remote clone on OIDF Web Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.OIDF_SPECS_HOST }}
          username: ${{ secrets.OIDF_USERID }}
          key: ${{ secrets.OIDF_USERID_KEY }}
          port: ${{ secrets.OIDF_SPECS_PORT }}
          script: |
              cd /var/www/openid.net/publication
              OLD_HEAD=$(git rev-parse HEAD)
              git status
              git pull
              NEW_HEAD=$(git rev-parse HEAD)
              for i in `git diff --name-only $OLD_HEAD $NEW_HEAD`; do echo "Purging cache of $i" ;  curl -X PURGE https://openid.net/specs/`basename $i`; echo "done" ; done
              echo "Purging /specs/ index cache"
              curl -X PURGE https://openid.net/specs/
