name: OIDF Publish
on:
  pull_request_review:
    types: 
    - submitted
  workflow_dispatch:

jobs:
  publish_to_specs:
    name: OIDF-Publish
    runs-on: ubuntu-latest
    environment: openid.net/specs/
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: openid/publication-checks
          path: publication-scripts
          ssh-key: ${{ secrets.OPENID_PUBLICATION_DEPLOY_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python requirements
        run: |
          cd ./publication-scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "::set-output name=path::$(which python)"

      - name: OpenID publication prep
        run : |
          mkdir ./to-publish
          ls
          echo "------"
          ls -l ./publication-scripts
          cd ./publication-scripts
          chmod +x ./publish.sh
          ls -l 
          head -n 20 publish.sh
          ./publish.sh
          cd ../to-publish
          ls

      - name: list remote /specs via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OIDF_SPECS_HOST }}
          username: ${{ secrets.OIDF_USERID }}
          key: ${{ secrets.OIDF_USERID_KEY }}
          port: ${{ secrets.OIDF_SPECS_PORT }}
          script: |
              whoami
              pwd
              ls
              ls /var/www/openid.net/htdocs/specs/

    #  - name: Copy OpenID publication to Web Server
    #    uses: appleboy/scp-action@v0.1.7
    #    with:
    #      host: ${{ secrets.OIDF_SPECS_HOST }}
    #      username: ${{ secrets.OIDF_USERID }}
    #      key: ${{ secrets.OIDF_USERID_KEY }}
    #      port: ${{ secrets.OIDF_SPECS_PORT }}
    #      source: "emptytest/test.txt"
    #      target: your_server_target_folder_path

  


