name: OIDF Publish
on:
  pull_request_review:
    types: 
    - submitted
  workflow_dispatch:

jobs:
  publish_to_specs:
    name: OIDF-Publish
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    environment: openid.net/specs/
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.OPENID_PUBLICATION_ACTION_DEPLOY_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: openid/publication-checks
          path: publication-scripts
          ssh-key: ${{ secrets.OPENID_PUBLICATION_DEPLOY_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python requirements
        run: |
          cd ./publication-scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "::set-output name=path::$(which python)"

      - name: OpenID publication prep
        run : |
          echo
          git checkout ${{ github.event.pull_request.head.ref }} 
          # echo "Current Branch: $(git branch --show-current)"
          echo "------"
          mkdir ./to-publish
          # ls -l ./publication-scripts
          cd ./publication-scripts
          chmod +x ./publish.sh
          ./publish.sh
          # pwd
          # ls -l
          # cat delete_files.txt
          cd ../to-publish
          git diff --name-status | grep "^D" | while read -r status filename; do
          # Issue git rm command for the file
            echo "Removing $filename from git index"
            git rm "../$filename"
          done
          # ls -l
          PUBLISH_LIST=$(ls)
          # GIT_TRACE=true
          echo "PUBLISH_LIST = $PUBLISH_LIST"
          cp ./* ../sync/specs
          cd ../sync/specs
          echo "In /sync/specs directory"
          # git ls-files --others --exclude-standard
          echo "Adding files to branch!"
          git add -A .
          git status
          # Setting Git User details
          git config --global user.name "OIDF GitHub Automation"
          git config --global user.email "github@oidf.org"
          echo "Commiting"
          git commit -m "$PUBLISH_LIST"
          echo "Merge and Push"
          # Check out target branch (e.g. main)
          git checkout ${{ github.event.pull_request.base.ref }}
          # merge head branch into base (e.g. main)
          git merge -X theirs --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge approved PR #${{ github.event.pull_request.number }}"
          # Push changes to remote
          git push origin ${{ github.event.pull_request.base.ref }}

      - name: Update remote clone on OIDF Web Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OIDF_SPECS_HOST }}
          username: ${{ secrets.OIDF_USERID }}
          key: ${{ secrets.OIDF_USERID_KEY }}
          port: ${{ secrets.OIDF_SPECS_PORT }}
          script: |
              cd /var/www/openid.net/publication
              git status
              git pull

  


