name: OIDF Publish
on:
  pull_request_review:
    types: 
    - submitted
  workflow_dispatch:

jobs:
  publish_to_specs:
    name: OIDF-Publish
    runs-on: ubuntu-latest
    environment: openid.net/specs/
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: openid/publication-checks
          path: publication-scripts
          ssh-key: ${{ secrets.OPENID_PUBLICATION_DEPLOY_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python requirements
        run: |
          cd ./publication-scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "::set-output name=path::$(which python)"

      - name: OpenID publication prep
        run : |
          # env
          PR_HEAD=$(jq '.pull_request.head.ref' $GITHUB_EVENT_PATH)

          mkdir ./to-publish
          ls -l ./publication-scripts
          cd ./publication-scripts
          chmod +x ./publish.sh
          ./publish.sh
          cd ../to-publish
          ls -l
          PUBLISH_LIST=$(ls)
          GIT_TRACE=true

         
          # CURRENT_BRANCH=$(git branch --show-current)
          # GRV=$(git rev-parse HEAD)
          # GIT_PARENT=$(git branch -r --contains $GRV)
          
          echo "PUBLISH_LIST = $PUBLISH_LIST"
          # echo "CURRENT_BRANCH = $CURRENT_BRANCH"
          # echo "GIT_PARENT = $GIT_PARENT"
          # pwd

          echo $(git status)
          echo $(git branch --show-current)
          
          git branch -a
          git checkout $PR_HEAD
          cp ./* ../sync/specs
          cd ../sync/specs
          echo "In /sync/specs now!"
          git ls-files --others --exclude-standard
          git config --global user.name "OIDF GitHub Automation"
          git config --global user.email "github@oidf.org"
          # echo "Create temporary branch!"
          # git branch tmp-action
          echo "Adding files to branch!"
          git add -A .
          echo "Commiting next!"
          git commit -m "$PUBLISH_LIST"
          # echo "Checkout Main!"
          # git checkout main
          # echo "Merge temporary branch into Main!"          
          # git merge tmp-action
          # echo "Delete temporary branch!"
          # git branch -d tmp-action
          echo "Pushing next!"
          git push

          INTENTIONALLY-FAIL

      - name: Update remote clone on OIDF Web Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OIDF_SPECS_HOST }}
          username: ${{ secrets.OIDF_USERID }}
          key: ${{ secrets.OIDF_USERID_KEY }}
          port: ${{ secrets.OIDF_SPECS_PORT }}
          script: |

              cd /var/www/openid.net/publication
              git status
              git pull

  


