name: OIDF Sync
on:
  workflow_dispatch:

jobs:
  sync_to_publication_server:
    name: OIDF-Sync
    runs-on: ubuntu-latest
    environment: openid.net/specs/
    steps:
      - name: initiate git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OIDF_SPECS_HOST }}
          username: ${{ secrets.OIDF_USERID }}
          key: ${{ secrets.OIDF_USERID_KEY }}
          port: ${{ secrets.OIDF_SPECS_PORT }}
          script: |
              pwd
              whoami
              ls
              cd /var/www/openid.net/publication
              git status
              git pull